-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_CODE,SUM(PRICE * SALES_AMOUNT) as SALES from PRODUCT join OFFLINE_SALE on PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID  
group by PRODUCT.PRODUCT_ID
order by SALES DESC,  PRODUCT.PRODUCT_CODE;