select YEAR(eo.DIFFERENTIATION_DATE) as YEAR,
(select MAX(SIZE_OF_COLONY) from ECOLI_DATA where YEAR(DIFFERENTIATION_DATE) = YEAR ) - eo.SIZE_OF_COLONY as YEAR_DEV,eo.ID as ID from ECOLI_DATA as eo
order by YEAR, YEAR_DEV




# SELECT YEAR(DIFFERENTIATION_DATE) YEAR, 
#     (SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA WHERE YEAR(DIFFERENTIATION_DATE) = YEAR) - SIZE_OF_COLONY as YEAR_DEV,
#     ID
# FROM ECOLI_DATA 
# ORDER BY YEAR, YEAR_DEV